# NUMPY 
LIBRARY

In [1]:
import numpy

In [2]:
numpy.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [3]:
a = numpy.array([2,32,4,5,65,46,4,4])

In [4]:
a

array([ 2, 32,  4,  5, 65, 46,  4,  4])

In [26]:
a.shape
#Shape - shows Row and Column

(8,)

In [8]:
aa = numpy.array([[1,2],[3,4],[5,6]])

In [9]:
aa

array([[1, 2],
       [3, 4],
       [5, 6]])

In [10]:
aa.shape

(3, 2)

In [12]:
row = numpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [16]:
# Reshape the data.
# But the number of data have to be the same.

In [19]:
aa.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
aa.dtype

dtype('int32')

In [21]:
aa.min()

1

In [22]:
aa.max()

6

In [25]:
aa.size
#Size - Total number of values

6

In [29]:
aa.data
#Shows data's memory address